### ISSUE TITLE
Chain Multiple TLC59711 Chips?

### ISSUE THREAD

**Issue by jepye** [adafruit/Adafruit_CircuitPython_TLC59711#10]
There doesn't seem to be any way to address additional TLC59711 chips/boards on the same bus.  This needs to be added as that chainability is one of the main advantages of the TLC59711.

**Comment by caternuson** [comment]
Hmm. That was added for the TLC5947:
https://github.com/adafruit/Adafruit_CircuitPython_TLC5947/issues/6
https://github.com/adafruit/Adafruit_CircuitPython_TLC5947/pull/8

Guess something similar is needed here.

**Comment by s-light** [comment]
i have implemented a multi-version some time ago..
https://github.com/s-light/Adafruit_CircuitPython_TLC59711/tree/multi
it is working..
but i had no time to clean up...
see: https://github.com/adafruit/Adafruit_CircuitPython_TLC59711/pull/5
if there is enough interest let me know and i will clean up and create a new pull request as soon as possible :-)

**Comment by kattni** [comment]
I believe this is now added!
