### ISSUE TITLE
Verify that documentation is complete

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_TLC59711#16]
There was concern that the documentation was not displaying properly. 

@jposada202020 Please verify this and resolve it if necessary. Otherwise, please close this issue.

**Comment by jposada202020** [comment]
@kattni This a picture after the merge
![image](https://user-images.githubusercontent.com/34255413/116496628-80c48400-a873-11eb-8373-a9486befd308.png)

**Comment by FoamyGuy** [comment]
resolved by #17. Thanks @jposada202020!
